import React, { useState } from 'react';
import { Calendar, MapPin, DollarSign, Sparkles, CheckCircle, Loader2, Users, Briefcase, Ticket, Send, FileText, AlertCircle, XCircle, Plus, Trash2, ListChecks, Lock, Unlock, ShieldAlert, Coins, RefreshCw, FileCode, Zap } from 'lucide-react';
import { generateEventDescription } from '../services/geminiService';
import PaymentGateway from '../components/PaymentGateway';
import { MOCK_ROSTER, MOCK_SERVICES } from '../mockData';
import { UserRole, CollabProposal, Milestone, SmartContractDraft } from '../types';
import { checkContentForViolation, MODERATION_WARNING_TEXT } from '../services/moderationService';
import ContractEditor from '../components/ContractEditor';
import { useToast } from '../contexts/ToastContext';

interface BookingHubProps {
  onBlockUser: () => void;
  onOpenExchange?: () => void;
}

const BookingHub: React.FC<BookingHubProps> = ({ onBlockUser, onOpenExchange }) => {
  const { notify } = useToast();
  const [activeTab, setActiveTab] = useState<'create' | 'manage'>('create');
  const [isGenerating, setIsGenerating] = useState(false);
  const [description, setDescription] = useState('');
  const [showPayment, setShowPayment] = useState(false);
  const [proposalToFund, setProposalToFund] = useState<CollabProposal | null>(null);
  
  const [isEditorOpen, setIsEditorOpen] = useState(false);
  const [viewingContract, setViewingContract] = useState<SmartContractDraft | null>(null);
  const [currentProposalId, setCurrentProposalId] = useState<string>('');

  const [eventName, setEventName] = useState('');
  const [selectedArtist, setSelectedArtist] = useState('');
  const [genre, setGenre] = useState('');
  const [rate, setRate] = useState('');
  const [currency, setCurrency] = useState<'USD' | 'ETH' | 'KALA'>('USD');
  
  const [paymentType, setPaymentType] = useState<'Lump Sum' | 'Milestone Based'>('Lump Sum');
  const [milestones, setMilestones] = useState<Milestone[]>([
    { id: 'm1', title: 'Initial Deposit', percentage: 50, status: 'Pending' },
    { id: 'm2', title: 'Project Completion', percentage: 50, status: 'Pending' }
  ]);

  const [myProposals, setMyProposals] = useState<CollabProposal[]>([
     {
       id: 'p-urgent-1',
       eventName: 'Last Minute Warehouse Party',
       artistName: 'DJ Havoc',
       status: 'Pending',
       budget: '1500',
       currency: 'USD',
       sentDate: new Date().toLocaleDateString(),
       paymentType: 'Lump Sum',
       isUrgent: true,
       receiverNote: 'Need a high-energy DJ for tonight!',
       contractData: {
          id: 'c-urgent-1',
          contractType: 'Performance Agreement',
          content: '// URGENT DRAFT...',
          lastEditedBy: 'User',
          version: 1,
          status: 'Pending Review'
       }
     },
     {
       id: 'p1',
       eventName: 'Neon Nights Vol. 1',
       artistName: 'Luna Eclipse',
       status: 'Accepted',
       budget: '1000',
       currency: 'USD',
       sentDate: '2023-10-10',
       receiverNote: 'Love the concept! Ready to sign.',
       paymentType: 'Lump Sum',
       contractData: {
          id: 'c-p1',
          contractType: 'Service Agreement',
          content: '// CONTRACT: Neon Nights\\n// STATUS: Active\\n\\ncontract ServiceAgreement {\\n  // Standard terms applied\\n}',
          lastEditedBy: 'Admin',
          version: 1,
          status: 'Active'
       }
     },
     {
       id: 'p2',
       eventName: 'Jazz Brunch',
       artistName: 'Astra Collective',
       status: 'Negotiation',
       budget: '0.5',
       currency: 'ETH',
       sentDate: '2023-10-12',
       paymentType: 'Milestone Based',
       milestones: [
         { id: 'm1', title: 'Booking Confirmation', percentage: 30, status: 'Released', proof: 'Signed Contract' },
         { id: 'm2', title: 'Performance', percentage: 70, status: 'Pending' }
       ],
       contractData: {
          id: 'c-p2',
          contractType: 'Service Agreement',
          content: '// CONTRACT: Jazz Brunch\\n// STATUS: Under Negotiation\\n// ADMIN NOTE: Adjusted liability clause.\\n\\ncontract ServiceAgreement {\\n  // Terms here...\\n}',
          lastEditedBy: 'Admin',
          version: 2,
          status: 'Negotiation',
          adminNotes: 'Please review the adjusted liability clause before accepting.'
       }
     }
  ]);

  const artists = MOCK_ROSTER.filter(r => r.role === UserRole.ARTIST);

  const handleAIGenerate = async () => {
    if (!selectedArtist || !genre) {
      notify("Please select an Artist and Genre first.", "warning");
      return;
    }
    const artistName = artists.find(a => a.id === selectedArtist)?.name || "Artist";
    setIsGenerating(true);
    const desc = await generateEventDescription(artistName, genre, 'High energy, immersive, futuristic');
    setDescription(desc);
    setIsGenerating(false);
    notify("Description generated by Gemini AI", "success");
  };

  const totalPercentage = milestones.reduce((sum, m) => sum + Number(m.percentage), 0);

  const handleSendProposal = () => {
    const contentToCheck = `${eventName} ${genre} ${description} ${milestones.map(m => m.title).join(' ')}`;

    if (checkContentForViolation(contentToCheck)) {
      onBlockUser();
      return;
    }

    if (!eventName || !rate || !selectedArtist) {
       notify("Please fill in the proposal name, budget, and select a main artist.", "warning");
       return;
    }

    if (paymentType === 'Milestone Based' && totalPercentage !== 100) {
      notify("Total milestone percentage must equal 100%.", "warning");
      return;
    }

    const artistName = artists.find(a => a.id === selectedArtist)?.name || 'Unknown Artist';

    const initialContract: SmartContractDraft = {
       id: `c-p${Date.now()}`,
       contractType: 'Service Agreement',
       content: `// DRAFT CONTRACT for ${eventName}\\n// Budget: ${rate} ${currency}\\n\\n${description}`,
       lastEditedBy: 'User',
       version: 1,
       status: 'Pending Review'
    };

    const newProposal: CollabProposal = {
      id: `p${Date.now()}`,
      eventName: eventName,
      artistName: artistName,
      status: 'Pending',
      budget: rate,
      currency: currency,
      sentDate: new Date().toLocaleDateString(),
      paymentType: paymentType,
      milestones: paymentType === 'Milestone Based' ? milestones : undefined,
      contractData: initialContract
    };

    setMyProposals([newProposal, ...myProposals]);
    notify("Proposal Sent! The artist will be notified and you can track progress in your dashboard.", "success");
    setActiveTab('manage');

    setEventName('');
    setRate('');
    setGenre('');
    setDescription('');
    setMilestones([{ id: 'm1', title: 'Initial Deposit', percentage: 50, status: 'Pending' }, { id: 'm2', title: 'Project Completion', percentage: 50, status: 'Pending' }]);
  };

  const handleFundEscrow = (proposal: CollabProposal) => {
    setProposalToFund(proposal);
    setShowPayment(true);
  };

  const handleOpenContract = (proposal: CollabProposal) => {
     if (proposal.contractData) {
        setViewingContract(proposal.contractData);
        setCurrentProposalId(proposal.id);
        setIsEditorOpen(true);
     }
  };

  const handleUpdateContract = (content: string) => {
     setMyProposals(prev => prev.map(p => {
        if (p.id === currentProposalId && p.contractData) {
           return {
              ...p,
              contractData: { ...p.contractData, content, lastEditedBy: 'User', version: p.contractData.version + 1 }
           };
        }
        return p;
     }));
     notify("Contract draft updated.", "info");
  };

  const handleContractStatusChange = (status: any, notes?: string) => {
     setMyProposals(prev => prev.map(p => {
        if (p.id === currentProposalId && p.contractData) {
           const newStatus = status === 'Active' ? 'Accepted' : status === 'Negotiation' ? 'Negotiation' : 'Rejected';
           return {
              ...p,
              status: newStatus,
              contractData: { ...p.contractData, status, adminNotes: notes }
           };
        }
        return p;
     }));
     notify(`Contract status changed to ${status}`, "info");
  };
  
  const sortedProposals = [...myProposals].sort((a, b) => Number(b.isUrgent) - Number(a.isUrgent));

  return (
    <div className="space-y-6">
       <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <Briefcase className="text-kala-secondary" /> Proposals & Contracts
          </h2>
          <p className="text-kala-400 text-sm">Create, negotiate, and fund proposals for any user on the portal.</p>
        </div>
        
        <div className="flex bg-kala-800 p-1 rounded-lg border border-kala-700">
          <button 
            onClick={() => setActiveTab('create')}
            className={`px-4 py-2 rounded-md text-sm font-bold transition-all flex items-center gap-2 ${
              activeT_ab === 'create'
              ? 'bg-kala-secondary text-kala-900 shadow-lg'
              : 'text-kala-400 hover:text-white'
            }`}
          >
            <Send className="w-4 h-4" /> New Proposal
          </button>
          <button 
            onClick={() => setActiveTab('manage')}
            className={`px-4 py-2 rounded-md text-sm font-bold transition-all flex items-center gap-2 ${
              activeTab === 'manage'
              ? 'bg-kala-secondary text-kala-900 shadow-lg'
              : 'text-kala-400 hover:text-white'
            }`}
          >
            <FileText className="w-4 h-4" /> Manage & Fund
            {myProposals.some(p => p.status === 'Accepted' || p.status === 'Negotiation' || p.isUrgent) && <span className={`w-2 h-2 rounded-full ${myProposals.some(p => p.isUrgent) ? 'bg-red-500 animate-pulse' : 'bg-yellow-500'}`}></span>}
          </button>
        </div>
       </div>

      {activeTab === 'create' ? (
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 animate-in fade-in">
          <div className="xl:col-span-2 bg-kala-800/50 backdrop-blur-md border border-kala-700 rounded-xl p-8">
            <div className="space-y-8">
              
              <div className="bg-red-900/20 border border-red-500/30 rounded-lg p-3 flex items-start gap-3">
                 <ShieldAlert className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
                 <p className="text-xs text-red-200">{MODERATION_WARNING_TEXT}</p>
              </div>

              <div>
                 <h3 className="text-sm font-bold text-kala-500 uppercase tracking-wider mb-4 border-b border-kala-700 pb-2">
                    1. Proposal Details
                 </h3>
                 <div className="mb-4">
                   <label className="block text-sm text-kala-300 mb-1 font-medium">Proposal / Event Name</label>
                   <input
                     type="text"
                     value={eventName}
                     onChange={(e) => setEventName(e.target.value)}
                     className="w-full bg-kala-900 border border-kala-700 rounded-lg px-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none"
                     placeholder="e.g. Summer Solstice Festival"
                   />
                 </div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                       <label className="block text-sm text-kala-300 mb-1 font-medium">Primary Recipient (Artist)</label>
                       <div className="relative">
                          <Users className="absolute left-3 top-2.5 w-4 h-4 text-kala-500" />
                          <select
                            value={selectedArtist}
                            onChange={(e) => setSelectedArtist(e.target.value)}
                            className="w-full bg-kala-900 border border-kala-700 rounded-lg pl-10 pr-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none appearance-none"
                          >
                             <option value="">Select Artist...</option>
                             {artists.map(a => <option key={a.id} value={a.id}>{a.name} ({a.location})</option>)}
                          </select>
                       </div>
                    </div>
                    <div>
                       <label className="block text-sm text-kala-300 mb-1 font-medium">Genre / Theme</label>
                       <input
                         type="text"
                         value={genre}
                         onChange={(e) => setGenre(e.target.value)}
                         className="w-full bg-kala-900 border border-kala-700 rounded-lg px-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none"
                         placeholder="e.g. Cyberpunk Jazz Night"
                       />
                    </div>
                 </div>
              </div>

              <div>
                 <h3 className="text-sm font-bold text-kala-500 uppercase tracking-wider mb-4 border-b border-kala-700 pb-2">
                    4. Contract & Payment
                 </h3>
                 <div className="mb-4">
                   <label className="block text-sm text-kala-300 mb-1 flex justify-between">
                     <span>Scope / Description (Auto-generated into Contract)</span>
                     <button
                       onClick={handleAIGenerate}
                       disabled={isGenerating}
                       className="text-xs text-kala-secondary hover:text-purple-400 flex items-center gap-1 transition-colors disabled:opacity-50"
                     >
                       {isGenerating ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                       {isGenerating ? 'Generating...' : 'Auto-Generate with Gemini'}
                     </button>
                   </label>
                   <textarea
                     rows={4}
                     value={description}
                     onChange={(e) => setDescription(e.target.value)}
                     className="w-full bg-kala-900 border border-kala-700 rounded-lg px-4 py-2 text-white focus:ring-1 focus:ring-kala-secondary outline-none resize-none"
                     placeholder="Describe the event vibes, capacity, and expectations..."
                   />
                 </div>

                 <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-4">
                    <div className="relative">
                      <label className="block text-sm text-kala-300 mb-1 font-medium">Budget / Rate</label>
                      <DollarSign className="absolute left-3 top-9 w-4 h-4 text-kala-500" />
                      <input
                        type="number"
                        value={rate}
                        onChange={(e) => setRate(e.target.value)}
                        className="w-full bg-kala-900 border border-kala-700 rounded-lg pl-10 pr-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none"
                        placeholder="1000"
                      />
                    </div>
                    <div>
                       <label className="block text-sm text-kala-300 mb-1 font-medium">Currency</label>
                       <div className="relative">
                          <Coins className="absolute left-3 top-9 w-4 h-4 text-kala-500" />
                          <select
                             value={currency}
                             onChange={(e) => setCurrency(e.target.value as 'USD' | 'ETH' | 'KALA')}
                             className="w-full bg-kala-900 border border-kala-700 rounded-lg pl-10 pr-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none appearance-none"
                          >
                             <option value="USD">USD (Fiat)</option>
                             <option value="ETH">ETH (Crypto)</option>
                             <option value="KALA">KALA (DAO Token)</option>
                          </select>
                       </div>
                    </div>
                    <div>
                       <label className="block text-sm text-kala-300 mb-1 font-medium">Payout Mode</label>
                       <select
                        value={paymentType}
                        onChange={(e) => setPaymentType(e.target.value as 'Lump Sum' | 'Milestone Based')}
                        className="w-full bg-kala-900 border border-kala-700 rounded-lg px-4 py-2.5 text-white focus:ring-1 focus:ring-kala-secondary outline-none appearance-none"
                       >
                         <option value="Lump Sum">Lump Sum Escrow</option>
                         <option value="Milestone Based">Milestone Based</option>
                       </select>
                    </div>
                 </div>

                 <div className="flex justify-end">
                    <button
                      onClick={() => onOpenExchange && onOpenExchange()}
                      className="text-xs text-kala-secondary hover:text-white font-bold flex items-center gap-1 bg-kala-900 px-3 py-1.5 rounded border border-kala-700 hover:border-kala-500 transition-colors"
                    >
                       <RefreshCw className="w-3 h-3" /> Need to swap for {currency}?
                    </button>
                 </div>
              </div>
              
              <div className="pt-4 border-t border-kala-700">
                <p className="text-xs text-kala-400 mb-4 flex items-center gap-2">
                   <AlertCircle className="w-4 h-4" />
                   Note: Funds are not deducted now. A smart contract draft will be created for Admin review.
                </p>
                <button
                  onClick={handleSendProposal}
                  className="w-full bg-gradient-to-r from-kala-secondary to-purple-600 text-white font-bold py-4 rounded-xl hover:opacity-90 transition-opacity shadow-lg shadow-purple-900/20 text-lg flex items-center justify-center gap-2"
                >
                  <Send className="w-5 h-5" /> Send Proposal & Create Draft
                </button>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-gradient-to-br from-indigo-900/50 to-kala-900 border border-indigo-700/30 rounded-xl p-6">
                <h3 className="text-lg font-semibold text-white mb-2">Smart Contract Flow</h3>
                <ul className="text-sm text-indigo-200/80 space-y-3">
                  <li className="flex gap-2">
                     <span className="bg-indigo-500/20 text-indigo-400 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold">1</span>
                     <span>Draft Proposal. This generates a legal/code wrapper.</span>
                  </li>
                  <li className="flex gap-2">
                     <span className="bg-indigo-500/20 text-indigo-400 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold">2</span>
                     <span>Admin reviews and approves/edits terms (Safety check).</span>
                  </li>
                  <li className="flex gap-2">
                     <span className="bg-indigo-500/20 text-indigo-400 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold">3</span>
                     <span>Negotiation: You can accept Admin edits or request changes.</span>
                  </li>
                  <li className="flex gap-2">
                     <span className="bg-indigo-500/20 text-indigo-400 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold">4</span>
                     <span>Contract Sealed. Escrow funded.</span>
                  </li>
                </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="space-y-6 animate-in slide-in-from-right-4 fade-in">
           {sortedProposals.map((prop) => (
             <div key={prop.id} className={`bg-kala-800/50 border rounded-xl p-6 transition-colors ${prop.isUrgent ? 'border-red-500/50 hover:border-red-400 shadow-lg shadow-red-900/10' : 'border-kala-700 hover:border-kala-500'}`}>
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-4">
                   <div>
                      <div className="flex items-center gap-2 mb-1 flex-wrap">
                        {prop.isUrgent && (
                            <span className="px-2 py-0.5 rounded text-xs font-bold border uppercase tracking-wider bg-red-500/10 text-red-400 border-red-500/20 flex items-center gap-1 animate-pulse">
                               <Zap className="w-3 h-3" />
                               Urgent Request
                            </span>
                        )}
                         <span className={`px-2 py-0.5 rounded text-xs font-bold border uppercase tracking-wider ${
                            prop.status === 'Accepted' ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                            prop.status === 'Rejected' ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                            prop.status === 'Negotiation' ? 'bg-orange-500/10 text-orange-400 border-orange-500/20' :
                            prop.status === 'Funded' ? 'bg-blue-500/10 text-blue-400 border-blue-500/20' :
                            'bg-yellow-500/10 text-yellow-400 border-yellow-500/20'
                         }`}>
                           {prop.status}
                         </span>
                         <span className="text-xs text-kala-500">Sent: {prop.sentDate}</span>
                      </div>
                      <h3 className="text-xl font-bold text-white">{prop.eventName}</h3>
                      <p className="text-sm text-kala-400">To: <span className="text-white font-medium">{prop.artistName}</span></p>
                   </div>
                   <div className="text-right">
                      <div className="text-2xl font-mono text-white font-bold">{prop.budget} {prop.currency}</div>
                      <div className="text-xs text-kala-500">{prop.paymentType}</div>
                   </div>
                </div>

                {prop.status === 'Negotiation' && (
                   <div className="bg-orange-500/10 border border-orange-500/30 p-3 rounded-lg flex justify-between items-center mb-4">
                      <div className="flex items-center gap-2">
                         <FileCode className="w-4 h-4 text-orange-400" />
                         <span className="text-sm text-orange-200">Admin has modified the contract terms. Action Required.</span>
                      </div>
                      <button
                        onClick={() => handleOpenContract(prop)}
                        className="text-xs bg-orange-500 hover:bg-orange-400 text-white px-3 py-1.5 rounded font-bold transition-colors"
                      >
                         Review & Accept
                      </button>
                   </div>
                )}

                <div className="flex flex-wrap items-center justify-between gap-4 border-t border-kala-700 pt-4">
                   <div className="flex gap-2">
                      {prop.contractData && (
                         <button
                           onClick={() => handleOpenContract(prop)}
                           className="text-xs bg-kala-900 hover:bg-kala-700 text-kala-300 px-3 py-2 rounded flex items-center gap-2 border border-kala-700"
                         >
                            <FileCode className="w-3 h-3" /> View Contract {prop.contractData.lastEditedBy === 'Admin' && <span className="text-orange-400 text-[10px]">(Edited)</span>}
                         </button>
                      )}
                   </div>

                   <div>
                      {prop.status === 'Accepted' && (
                         <button
                           onClick={() => handleFundEscrow(prop)}
                           className="bg-green-600 hover:bg-green-500 text-white font-bold px-6 py-2 rounded-lg transition-colors flex items-center gap-2 shadow-lg shadow-green-900/20"
                         >
                            <DollarSign className="w-4 h-4" /> Fund Escrow Now
                         </button>
                      )}
                      {prop.status === 'Funded' && (
                         <button disabled className="bg-kala-700 text-kala-400 font-bold px-6 py-2 rounded-lg flex items-center gap-2 cursor-not-allowed">
                            <CheckCircle className="w-4 h-4" /> Contract Active
                         </button>
                      )}
                   </div>
                </div>
             </div>
           ))}
        </div>
      )}

      {showPayment && proposalToFund && (
         <PaymentGateway
           amount={proposalToFund.budget}
           currency={proposalToFund.currency || 'USD'}
           itemDescription={`Escrow Funding for ${proposalToFund.eventName}`}
           onSuccess={(method) => {
              setMyProposals(prev => prev.map(p => p.id === proposalToFund.id ? {...p, status: 'Funded'} : p));
              notify(`Escrow Funded via ${method}! Smart Contract Deployed.`, "success");
              setShowPayment(false);
              setProposalToFund(null);
           }}
           onCancel={() => { setShowPayment(false); setProposalToFund(null); }}
         />
      )}

      {isEditorOpen && viewingContract && (
         <ContractEditor
            contract={viewingContract}
            userRole={UserRole.ARTIST} 
            onClose={() => setIsEditorOpen(false)}
            onSave={handleUpdateContract}
            onStatusChange={handleContractStatusChange}
            onBlockUser={onBlockUser}
         />
      )}
    </div>
  );
};

export default BookingHub;
